name: kernelscan
version: 0.3.0
summary: fast kernel source error message scanner
description: kernelscan parses the kernel source and extracts all the kernel error messages, It also reformats the messages by joining multi-line literal strings to make it easier to look for error message text.
type: app
grade: stable

confinement: strict

parts:
    kernelscan:
        plugin: make
        source: .
        build-packages:
            - gcc
            - make

        stage-packages:
            - wamerican
        prime:
            - usr/bin
            - usr/share/dict

apps:
    kernelscan:
        command: usr/bin/kernelscan
        plugs: [home]

