name: kernelscan
version: git
summary: fast kernel source error message scanner
description: kernelscan parses the kernel source and extracts all the kernel error messages, It also reformats the messages by joining multi-line literal strings to make it easier to look for error message text.
type: app
grade: stable
base: core18
confinement: strict

parts:
    kernelscan:
        plugin: make
        source: git://kernel.ubuntu.com/cking/kernelscan
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"
        build-packages:
            - gcc
            - make

        stage-packages:
            - wamerican
        prime:
            - usr/bin
            - usr/share/dict

apps:
    kernelscan:
        command: usr/bin/kernelscan
        plugs: [home]

